name: Generate Daily Key

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate-key:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Generate Key
        run: |
          pip install --upgrade pip
          mkdir -p keys
          python generatekey.py
      - name: Commit and Push Keys
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add keys/
          git commit -m "Add key for $(date -u +'%Y-%m-%d')" || echo "No changes to commit"
          git push
